$schema: "http://json-schema.org/draft-04/schema#"

id: "project"
title: Project
type: object
program: '*'
project: '*'
category: administrative
description: >
  Any specifically defined piece of work that is undertaken or attempted to meet a single
  requirement. (NCIt C47885)
additionalProperties: false
submittable: true
validators: null

systemProperties:
  - id
  - state
  - released
  - releasable
  - intended_release_date

required:
  - code
  - type
  - name
  - state
  - programs
  - dbgap_accession_number
  - data_contributor

uniqueKeys:
  - [ id ]
  - [ code ]

links:
  - name: programs
    backref: projects
    label: member_of
    target_type: program
    multiplicity: many_to_one
    required: true

constraints: null

properties:

  availability_type:
    description: "Is the project open or restricted?"
    enum:
      - Open
      - Restricted

  code:
    type: string
    description: "Unique identifier for the project."

  contact_name:
    type: string
    description: "Name of the person who is the point of contact for data access questions"

  contact_email:
    type: string
    description: Email of the point of contact for data access questions

  data_contributor:
    description: "Organization contributing data"
    type: string

  data_source_project:
    description: "Project name(s) as defined in the contributing data source system (e.g., COHORT A, APOLLO OV, APOLLO LUAD, PROMETHEUS 8A)"
    type: string

  dbgap_accession_number:
    type: string
    description: "The dbgap accession number provided for the project."

  description:
    description: "Short study or dataset description shown in Explorer."
    type: string

  id:
    $ref: "_definitions.yaml#/UUID"
    systemAlias: node_id
    description: "UUID for the project." # TOREVIEW

  name:
    type: string
    description: "Display name/brief description for the project." # TOREVIEW

  release_status:
    description: "Whether the data is pre-release or publicly released"
    enum:
      - Pre-released
      - Released

  state:
    description: |
      The possible states a project can be in. All but 'open' are
      equivalent to some type of locked state.
    default: open
    enum:
        # open: the only state users can perform 'upload' actions
        # possible actions in `open`:
        #   - upload (no state change)
        #   - review -> review
        #   - release (project.released -> true)
        - open

        # locked: admin has locked project for review
        # possible actions in `locked`:
        #   - open -> open
        #   - submit -> submitted
        #   - release (project.released -> true)
        - review

        # submitted: An admin has submitted project, it is locked against
        #            upload.
        # possible actions in `submitted`:
        #   - process -> processing
        #   - release (project.released -> true)
        - submitted

        # processing: The system is processing data in the project and
        #             is locked against upload and submission
        #   - (system transition to open)
        #   - release (project.released -> true)
        - processing


        # closed: The closed state means that no further action
        #         can be taken on the project
        #   - (system transition to open)
        #   - release (project.released -> true)
        - closed

  type:
    type: string

  programs:
    $ref: "_definitions.yaml#/to_one"
    description: >
      The program to which the project belongs.
